CREATE DATABASE `ds_0` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci';
CREATE DATABASE `ds_1` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci';

CREATE TABLE `ds_0`.`t_order_0` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_0`.`t_order_1` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_0`.`t_order_2` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_0`.`t_order_3` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_0`.`t_order_4` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_0`.`t_order_5` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_0`.`t_order_6` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_0`.`t_order_7` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_0`.`t_order_8` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_0`.`t_order_9` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_0`.`t_order_10` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_0`.`t_order_11` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_0`.`t_order_12` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_0`.`t_order_13` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_0`.`t_order_14` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_0`.`t_order_15` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ds_1`.`t_order_0` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_1`.`t_order_1` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_1`.`t_order_2` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_1`.`t_order_3` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_1`.`t_order_4` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_1`.`t_order_5` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_1`.`t_order_6` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_1`.`t_order_7` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_1`.`t_order_8` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_1`.`t_order_9` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_1`.`t_order_10` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_1`.`t_order_11` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_1`.`t_order_12` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_1`.`t_order_13` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_1`.`t_order_14` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ds_1`.`t_order_15` (`order_id` bigint(20) NOT NULL,`user_id` bigint(20) DEFAULT NULL, `description` varchar(255) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
